In [27]:
import pandas as pd
file="Presidents2.csv"
df = pd.read_csv(file)
#print(df['National total votes'])
df.isnull()

,President,Years in office,Year first inaugurated,Age at inauguration,State elected from,# of electoral votes,# of popular votes,National total votes,Total electoral votes,Rating points,Political Party,Occupation,College,% electoral,% popular
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
156,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
157,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
158,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
159,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
160,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
161,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
162,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
163,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
164,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
165,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
166,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
167,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
168,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
169,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
170,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
171,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
172,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
173,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
174,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
175,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
176,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
177,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
178,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
179,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
180,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
181,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
182,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
183,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
184,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True

In [28]:
df

,President,Years in office,Year first inaugurated,Age at inauguration,State elected from,# of electoral votes,# of popular votes,National total votes,Total electoral votes,Rating points,Political Party,Occupation,College,% electoral,% popular
0,George Washington,8,1789,57,Virginia,69,NA(),NA(),69,842,None,Planter,None,100,NA()
1,John Adams,4,1797,61,Massachusetts,132,NA(),NA(),139,598,Federalist,Lawyer,Harvard,95,NA()
2,Thomas Jefferson,8,1801,57,Virginia,73,NA(),NA(),137,711,Democratic-Republican,"Planter, Lawyer",William and Mary,53.3,NA()
3,James Madison,8,1809,57,Virginia,122,NA(),NA(),176,567,Democratic-Republican,Lawyer,Princeton,69.3,NA()
4,James Monroe,8,1817,58,Virginia,183,NA(),NA(),221,602,Democratic-Republican,Lawyer,William and Mary,82.8,NA()
5,John Quincy Adams,4,1825,57,Massachusetts,84,NA(),NA(),261,564,Democratic-Republican,Lawyer,Harvard,32.2,NA()
6,Andrew Jackson,8,1829,61,Tennessee,178,"6,42,553","11,48,018",261,632,Democrat,Lawyer,None,68.2,56
7,Martin Van Buren,4,1837,54,New York,170,"7,64,176","15,03,534",294,429,Democrat,Lawyer,None,57.8,50.8
8,William Henry Harrison,0.8,1841,68,Ohio,234,"12,75,390","24,11,808",294,329,Whig,Soldier,Hampden-Sydney,79.6,52.9
9,James K. Polk,4,1845,49,Tennessee,170,"13,39,494","27,03,659",275,632,Democrat,Lawyer,U. of North Carolina,61.8,49.5
10,Zachary Taylor,1,1849,64,Louisiana,163,"13,61,393","28,79,184",290,447,Whig,Soldier,None,56.2,47.3
11,Franklin Pierce,4,1853,48,New Hampshire,254,"16,07,510","31,61,830",296,286,Democrat,Lawyer,Bowdoin,85.8,50.8
12,James Buchanan,4,1857,65,Pennsylvania,174,"18,36,072","40,54,647",296,259,Democrat,Lawyer,Dickinson,58.8,45.3
13,Abraham Lincoln,4,1861,52,Illinois,180,"18,65,908","46,85,561",303,900,Republican,Lawyer,None,59.4,39.8
14,Ulysses S. Grant,8,1869,46,Illinois,214,"30,13,650","57,22,440",294,403,Republican,Soldier,US Military Academy,72.8,52.7
15,Rutherford B. Hayes,4,1877,54,Ohio,185,"40,34,311","84,13,101",369,477,Republican,Lawyer,Kenyon,50.1,48
16,James A. Garfield,0.5,1881,49,Ohio,214,"44,46,158","92,10,420",369,444,Republican,Lawyer,Williams,58,48.3
17,Grover Cleveland,4,1885,47,New York,219,"48,74,621","1,00,49,754",401,576,Democrat,Lawyer,None,54.6,48.5
18,Benjamin Harrison,4,1889,55,Indiana,233,"54,43,892","1,13,83,320",401,426,Republican,Lawyer,Miami,58.1,47.8
19,Grover Cleveland,4,1893,55,New York,277,"55,51,883","1,20,56,097",444,576,Democrat,Lawyer,None,62.4,46.1
20,William McKinley,4,1897,54,Ohio,271,"71,08,480","1,39,35,738",447,601,Republican,Lawyer,Allegheny College,60.6,51
21,William Howard Taft,4,1909,51,Ohio,321,"76,76,258","1,48,82,734",483,491,Republican,Lawyer,Yale,66.5,51.6
22,Woodrow Wilson,8,1913,56,New Jersey,435,"62,93,152","1,50,40,963",531,723,Democrat,Educator,Princeton,81.9,41.8
23,Warren G. Harding,2,1921,55,Ohio,404,"1,61,33,314","2,67,53,786",531,326,Republican,Editor,None,76.1,60.3
24,Herbert Hoover,4,1929,54,California,444,"2,14,11,991","3,67,90,364",531,400,Republican,Engineer,Stanford,83.6,58.2
25,Franklin Roosevelt,12,1933,51,New York,472,"2,28,25,016","3,97,49,382",531,876,Democrat,Lawyer,Harvard,88.9,57.4
26,Dwight D. Eisenhower,8,1953,62,New York,442,"3,39,36,137","6,15,51,118",531,699,Republican,Soldier,US Military Academy,83.2,55.1
27,John F. Kennedy,3,1961,43,Massachusetts,303,"3,42,21,344","6,88,28,960",537,704,Democrat,Author,Harvard,56.4,49.7
28,Richard M. Nixon,5,1969,56,New York,301,"3,17,85,148","7,32,03,370",538,477,Republican,Lawyer,Whittier,55.9,43.4
29,Jimmy Carter,4,1977,52,Georgia,297,"4,08,30,763","8,15,55,889",538,518,Democrat,Businessman,US Naval Academy,55.2,50.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,Massachusetts,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,Michigan,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,Minnesota,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,Mississippi,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,Missouri,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,Montana,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,Nebraska,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,Nevada,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,New Hampshire,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,New Jersey,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,New Mexico,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,New York,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,North Carolina,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,North Dakota,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,Ohio,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,Oklahoma,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,Oregon,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,Pennsylvania,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,Rhode Island,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,South Carolina,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,South Dakota,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,Tennessee,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,Texas,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,Utah,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,Vermont,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,Virginia,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,Washington,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,West Virginia,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,Wisconsin,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,Wyoming,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df['# of electoral votes'].fillna(0, inplace=True)

In [31]:
df['Years in office'].fillna(0, inplace=True)

In [32]:
df

,President,Years in office,Year first inaugurated,Age at inauguration,State elected from,# of electoral votes,# of popular votes,National total votes,Total electoral votes,Rating points,Political Party,Occupation,College,% electoral,% popular
0,George Washington,8,1789,57,Virginia,69,NA(),NA(),69,842,None,Planter,None,100,NA()
1,John Adams,4,1797,61,Massachusetts,132,NA(),NA(),139,598,Federalist,Lawyer,Harvard,95,NA()
2,Thomas Jefferson,8,1801,57,Virginia,73,NA(),NA(),137,711,Democratic-Republican,"Planter, Lawyer",William and Mary,53.3,NA()
3,James Madison,8,1809,57,Virginia,122,NA(),NA(),176,567,Democratic-Republican,Lawyer,Princeton,69.3,NA()
4,James Monroe,8,1817,58,Virginia,183,NA(),NA(),221,602,Democratic-Republican,Lawyer,William and Mary,82.8,NA()
5,John Quincy Adams,4,1825,57,Massachusetts,84,NA(),NA(),261,564,Democratic-Republican,Lawyer,Harvard,32.2,NA()
6,Andrew Jackson,8,1829,61,Tennessee,178,"6,42,553","11,48,018",261,632,Democrat,Lawyer,None,68.2,56
7,Martin Van Buren,4,1837,54,New York,170,"7,64,176","15,03,534",294,429,Democrat,Lawyer,None,57.8,50.8
8,William Henry Harrison,0.8,1841,68,Ohio,234,"12,75,390","24,11,808",294,329,Whig,Soldier,Hampden-Sydney,79.6,52.9
9,James K. Polk,4,1845,49,Tennessee,170,"13,39,494","27,03,659",275,632,Democrat,Lawyer,U. of North Carolina,61.8,49.5
10,Zachary Taylor,1,1849,64,Louisiana,163,"13,61,393","28,79,184",290,447,Whig,Soldier,None,56.2,47.3
11,Franklin Pierce,4,1853,48,New Hampshire,254,"16,07,510","31,61,830",296,286,Democrat,Lawyer,Bowdoin,85.8,50.8
12,James Buchanan,4,1857,65,Pennsylvania,174,"18,36,072","40,54,647",296,259,Democrat,Lawyer,Dickinson,58.8,45.3
13,Abraham Lincoln,4,1861,52,Illinois,180,"18,65,908","46,85,561",303,900,Republican,Lawyer,None,59.4,39.8
14,Ulysses S. Grant,8,1869,46,Illinois,214,"30,13,650","57,22,440",294,403,Republican,Soldier,US Military Academy,72.8,52.7
15,Rutherford B. Hayes,4,1877,54,Ohio,185,"40,34,311","84,13,101",369,477,Republican,Lawyer,Kenyon,50.1,48
16,James A. Garfield,0.5,1881,49,Ohio,214,"44,46,158","92,10,420",369,444,Republican,Lawyer,Williams,58,48.3
17,Grover Cleveland,4,1885,47,New York,219,"48,74,621","1,00,49,754",401,576,Democrat,Lawyer,None,54.6,48.5
18,Benjamin Harrison,4,1889,55,Indiana,233,"54,43,892","1,13,83,320",401,426,Republican,Lawyer,Miami,58.1,47.8
19,Grover Cleveland,4,1893,55,New York,277,"55,51,883","1,20,56,097",444,576,Democrat,Lawyer,None,62.4,46.1
20,William McKinley,4,1897,54,Ohio,271,"71,08,480","1,39,35,738",447,601,Republican,Lawyer,Allegheny College,60.6,51
21,William Howard Taft,4,1909,51,Ohio,321,"76,76,258","1,48,82,734",483,491,Republican,Lawyer,Yale,66.5,51.6
22,Woodrow Wilson,8,1913,56,New Jersey,435,"62,93,152","1,50,40,963",531,723,Democrat,Educator,Princeton,81.9,41.8
23,Warren G. Harding,2,1921,55,Ohio,404,"1,61,33,314","2,67,53,786",531,326,Republican,Editor,None,76.1,60.3
24,Herbert Hoover,4,1929,54,California,444,"2,14,11,991","3,67,90,364",531,400,Republican,Engineer,Stanford,83.6,58.2
25,Franklin Roosevelt,12,1933,51,New York,472,"2,28,25,016","3,97,49,382",531,876,Democrat,Lawyer,Harvard,88.9,57.4
26,Dwight D. Eisenhower,8,1953,62,New York,442,"3,39,36,137","6,15,51,118",531,699,Republican,Soldier,US Military Academy,83.2,55.1
27,John F. Kennedy,3,1961,43,Massachusetts,303,"3,42,21,344","6,88,28,960",537,704,Democrat,Author,Harvard,56.4,49.7
28,Richard M. Nixon,5,1969,56,New York,301,"3,17,85,148","7,32,03,370",538,477,Republican,Lawyer,Whittier,55.9,43.4
29,Jimmy Carter,4,1977,52,Georgia,297,"4,08,30,763","8,15,55,889",538,518,Democrat,Businessman,US Naval Academy,55.2,50.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,Massachusetts,4,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,Michigan,1,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,Minnesota,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,Mississippi,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,Missouri,1,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,Montana,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,Nebraska,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,Nevada,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,New Hampshire,1,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,New Jersey,1,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,New Mexico,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,New York,9,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,North Carolina,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,North Dakota,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,Ohio,6,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,Oklahoma,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,Oregon,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,Pennsylvania,1,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,Rhode Island,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,South Carolina,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,South Dakota,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,Tennessee,3,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,Texas,3,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,Utah,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,Vermont,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,Virginia,5,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,Washington,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,West Virginia,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,Wisconsin,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,Wyoming,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
df.loc[df['President']=='President']

,President,Years in office,Year first inaugurated,Age at inauguration,State elected from,# of electoral votes,# of popular votes,National total votes,Total electoral votes,Rating points,Political Party,Occupation,College,% electoral,% popular
35,President,Years in office,Year first inaugurated,Age at inauguration,State elected from,# of electoral votes,Total electoral votes,# of popular votes,National total votes,Rating points,Political Party,Occupation,College,% electoral,% popular
65,President,Years in office,Year first inaugurated,Age at inauguration,State elected from,# of electoral votes,# of popular votes,National total votes,Total electoral votes,Rating points,Political Party,Occupation,College,% electoral,% popular

In [56]:
df.drop(df['President']=='President', inplace=True)

KeyError: '[False False False False False False False False False False False False\n False False False False False False False False False False False False\n False False False False False False False False False False False  True\n False False False False False False False False False False False False\n False False False False False False False False False False False False\n False False False False False  True False False False False False False\n False False False False False False False False False False False False\n False False False False False False False False False False False False\n False False False False False False False False False False False False\n False False False False False False False False False False False False\n False False False False False False False False False False False False\n False False False False False False False False False False False False\n False False False False False False False False False False False False\n False False False False False False False False False False False False\n False False False False False False False False False False False False\n False False False False False] not found in axis'

KeyError: "['President'] not found in axis"