In [1]:
import pandas as pd
file_name="data/_Aug2-107561.xlsx"
dfs = pd.read_excel(file_name, sheet_name="Sheet1")

KeyboardInterrupt:

In [40]:

nan_rows = dfs[dfs['tel_Other'].isnull()]

nan_rows.to_excel("data/no_nos.xlsx")

In [35]:
import numpy as np
df = dfs[pd.notnull(dfs['tel_Other'])]

In [38]:
df.to_csv("data/mixed.csv")

In [41]:
duplicateRowsDF = df[df.duplicated(['tel_Other'])]

In [44]:
duplicateRowsDF.to_excel("data/duplicate.xlsx")

In [46]:
df3 = pd.merge(df, duplicateRowsDF, how='outer', indicator=True).query('_merge=="left_only"').drop('_merge',1)

In [50]:
df3.to_csv("data/unique.csv")

In [54]:
#final
import pandas as pd
file_name="data/_Aug2-107561.xlsx"
dfs = pd.read_excel(file_name, sheet_name="Sheet1")

nan_rows = dfs[dfs['tel_Other'].isnull()]
nan_rows.to_excel("data/no_nos.xlsx")

df3 = pd.merge(dfs, nan_rows, how='outer', indicator=True).query('_merge=="left_only"').drop('_merge',1)


duplicateRowsDF = df3[df3.duplicated(['tel_Other'])]
duplicateRowsDF.to_excel("data/duplicate.xlsx")

df3 = pd.merge(df3, duplicateRowsDF, how='outer', indicator=True).query('_merge=="left_only"').drop('_merge',1)
k_uni=df3.tel_Other.str.split(';').str[1]

df3['alt']=k_uni

df3['tel_Other'] = df3['tel_Other'].str.split(';').str[0]

#remove from - fro tel_no
df3['tel_Other'] = df3['tel_Other'].str.split('-').str[1]
#remove from -0- from alt
df3['alt'] = df3['alt'].str.split('-0-').str[1]

#df3.to_csv("data/unique.csv")
#convert csv to xlsx
writer = pd.ExcelWriter('data/unique.xlsx')
df3.to_excel(writer, index = False)
writer.save()

#alteranate number for duplicate
df_n=pd.read_excel("data/duplicate.xlsx",sheet_name="Sheet1")
k=df_n.tel_Other.str.split(';').str[1]

df_n['alt']=k
df_n['tel_Other'] = df_n['tel_Other'].str.split(';').str[0]
#remove from - fro tel_no
df_n['tel_Other'] = df_n['tel_Other'].str.split('-').str[1]
#remove from -0- from alt
df_n['alt'] = df_n['alt'].str.split('-0-').str[1]

df_n.to_excel("data/duplicate.xlsx")

#alteranate number for unique
#df_uni=pd.read_excel("data/unique.xlsx",sheet_name="Sheet1")
#k_uni=df_uni.tel_Other.str.split(';').str[1]

#df_uni['alt']=k_uni
#df_uni['tel_Other'] = df_uni['tel_Other'].str.split(';').str[0]
#writer_uni = pd.ExcelWriter('data/unique.xlsx')
#df_uni.to_excel(writer_uni, index = False)
#writer.save()

In [51]:
df_10=pd.read_excel("data/duplicate.xlsx",sheet_name="Sheet1")
df_10['tel_Other'] = df_10['tel_Other'].str.split('-').str[1]
df_10['alt'] = df_10['alt'].str.split('-0-').str[1]

In [52]:

df_10

,candidateName,companyName,companyName2,designation,emailAddress,experienceMas,locationCurrentMas,lastUpdate,qualificationMas,qualificationMas2,salary,tel_Other,alt
1284,Dhruti Trivedi,Hats & Beards,NaN,Freelance Content Writer,dhruti.trivedi90@gmail.com,7 Month(s),Ahmedabad,16 Aug; 2017,BA (Arts),MA (Arts),NaN,9000000000,NaN
2514,kapil Dev,Airmail Service Pvt Ltd,NaN,Supervisor/ Resolution Expert,kapil_dev131@yahoo.com,5 Year(s) 10 Month(s),Chandigarh,16 Aug; 2017,B.Sc. (Science),NaN,Rs. 3.0 lacs,9478287437,NaN
3257,MOHD FURKAN,Kotak Mahindra Bank,IDBI BANK LTD,Deputy manager,furkan.mohd@yahoo.in,7 Year(s) 5 Month(s),Delhi,16 Aug; 2017,MA (Arts),BA (Arts),Rs. 3.5 lacs,8527690595,NaN
3822,Rohit Motkari,Central Government of India,Motkari Associates,Examiner of Trademark,rohitmotkari@gmail.com,4 Year(s) 3 Month(s),Mumbai,16 Aug; 2017,BL/LLB,NaN,Rs. 4.2 lacs,9000000000,NaN
3884,GaganDeep,Infogain India Pvt Ltd.,NaN,Software Engineer,gagan.btechcse12@outlook.com,1 Year(s) 2 Month(s),Noida/ Greater Noida,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,Rs. 3.92 lacs,8377868648,NaN
4179,naveen kumaar,Vasan Health Care,NaN,NaN,drnavortho@gmail.com,3 Year(s) 9 Month(s),Madurai,16 Aug; 2017,NaN,Master of Dental Surgery (MDS),Rs. 12.5 lacs,7708185982,NaN
4272,Mitali shah,aaryam art academy,ideal experiential learing,marketing + Educator,mdgsk09@gmail.com,7 Year(s),Ahmedabad,16 Aug; 2017,BCA (Computer Application),NaN,Rs. 3.6 lacs,9000000000,NaN
4476,POORNIMA RAMARAO,Surya Industries,RBS Business Services Pvt Ltd,Executive Administrator,poornimatimes@gmail.com,2 Year(s) 10 Month(s),Chennai,16 Aug; 2017,B.Com. (Commerce),ICWA,Rs. 1.66 lacs,9940692946,NaN
5654,SURESH AKKIRAJU,Fresher,NaN,Fresher,sureshakkiraju1@gmail.com,Fresher,Hyderabad/ Secunderabad,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,NaN,8978255028,NaN
5682,ADITYA MURTY,Angel quality solutions pvt ltd,NaN,NaN,jerrytechnician23@gmail.com,3 Year(s) 2 Month(s),Delhi,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,Rs. 4.8 lacs,9821505514,NaN
5817,Kajal Shah,Mansukh Securities And Finance Ltd,NaN,Derivative analyst,kajal.glsmba14@gmail.com,7 Month(s),Ahmedabad,16 Aug; 2017,NaN,MBA/ PGDM,Rs. 2.15 lacs,9909051236,NaN
5845,Gagan Deep,Infogain India Pvt Ltd,NaN,Software Engineer,gagan.btechcse12@outlook.com,2 Year(s) 6 Month(s),Noida/ Greater Noida,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,Rs. 4.65 lacs,8377868648,NaN
7188,Alok Kumar,Capgemini India Pvt Ltd,Infosys Technologies Ltd,Consultant,alok.gupta54321@gmail.com,3 Year(s),Bengaluru/ Bangalore,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,Rs. 6.0 lacs,9000000000,NaN
7800,vinay,Exclusife Technosoft Pvt Ltd,NaN,Assistant Manager - Client service and sales,vinayktandon93@gmail.com,4 Year(s),Noida/ Greater Noida,16 Aug; 2017,BCA (Computer Application),NaN,Rs. 3.0 lacs,9999999999,NaN
9212,ShindeRahul,Fresher,NaN,Fresher,rsrahulshinde5@hotmail.com,Fresher,Mumbai,16 Aug; 2017,12th & Not Pursuing Graduation,12th & Not Pursuing Graduation,NaN,9022894455,NaN
9529,Fajal Mulani,Allied Digital Services Ltd,NaN,Network Engineer,fajal.mulani1@gmail.com,1 Year(s) 5 Month(s),Pune,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,Rs. 1.8 lacs,9022105484,NaN
9798,MERSI NEDARPALLI,Adfc Pvt Ltd,NaN,NaN,mnedarpalli@gmail.com,3 Year(s) 11 Month(s),Pune,16 Aug; 2017,NaN,M.Com. (Commerce),Rs. 4.0 lacs,9420732866,NaN
11075,Bharath B,Rangsons defence solutions,NaN,Associate design Engineer,bharath.bhaskar6@gmail.com,1 Year(s),Bengaluru/ Bangalore,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,Rs. 3.0 lacs,9880960734,NaN
11641,Suneetha C,mPortal ( BroadSoft ),Valuepoint Systems Pvt Ltd,India; partner,suneethachandrappa@gmail.com,16 Year(s) 8 Month(s),Bengaluru/ Bangalore,16 Aug; 2017,NaN,NaN,Rs. 30.0 lacs,9845250212,NaN
11725,Swapnil Balsaraf,Accenture Services Pvt. Ltd.,NaN,Senior Software Engineer in Mainframes capability,swapnil.b.balsaraf@gmail.com,5 Year(s),Pune,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,NaN,9423011616,NaN
12158,AJAY KUMAR,Fresher,NaN,Fresher,erajaykr@gmail.com,1 Year(s) 1 Month(s),Delhi,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,NaN,9555572853,NaN
12160,udaya bhaskar ravi,Fresher,NaN,Fresher,uday.ravi347@gmail.com,Fresher,Hyderabad/ Secunderabad,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,NaN,9908928989,NaN
12162,DipaliPuranik,icici bank ltd,Citicorp Finanace India Limited,Team Member ( Loan MIS Preparation),dipali.puranik@gmail.com,3 Year(s) 9 Month(s),Mumbai,16 Aug; 2017,B.Com. (Commerce),NaN,Rs. 1.1 lacs,8554954662,NaN
12164,Paul Mani,Accounts Officer,Samudra Biopharma Pvt Ltd,Accounts Officer,pmatchayha@gmail.com,25 Year(s) 8 Month(s),Chennai,16 Aug; 2017,B.Com. (Commerce),NaN,Rs. 5.0 lacs,7205370874,NaN
12166,ASHISH RANJAN,Viom Networks Ltd,NaN,Manager,ashishranjan02@gmail.com,10 Year(s) 1 Month(s),Delhi,16 Aug; 2017,BL/LLB,NaN,Rs. 13.0 lacs,9811669863,NaN
12168,binduj setty,Mount Carmel college,NaN,Lecture,bindujsetty@gmail.com,2 Year(s) 6 Month(s),Bengaluru/ Bangalore,16 Aug; 2017,B.Sc. (Science),M.Sc. (Science),Rs. 2.5 lacs,8197429468,NaN
12170,Ranjit Konwar,HCCBPL,NaN,NaN,ranjit_konwar@yahoo.com,17 Year(s),Guwahati,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,Rs. 7.73 lacs,9085079279,NaN
12172,VIVEKANANDA BADIGER,Fresher,NaN,Fresher,bvivek20@gmail.com,2 Year(s),Bengaluru/ Bangalore,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,NaN,9964046340,NaN
12174,PINTU KUMAR,ROLLATAINERS LTD,NaN,ACCOUNTS EXECUTIVE,coolguy0288@gmail.com,4 Year(s) 9 Month(s),Gurgaon,16 Aug; 2017,B.Com. (Commerce),NaN,Rs. 1.98 lacs,7404923066,7737345496
12176,Nahush Deodhar,Cognizant Technology Solutions,NaN,Associate Consultant,nahush.deodhar@gmail.com,8 Year(s) 6 Month(s),Pune,16 Aug; 2017,B.Com. (Commerce),NaN,Rs. 5.92 lacs,8793349263,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103822,NEETHU PAULSON,Currently Unemployed,Thinksoft Global Services ; Chennai,Currently Unemployed,neethumekkat@gmail.com,1 Year(s),Bengaluru/ Bangalore,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,Rs. 1.04 lacs,9632380578,NaN
103824,VOOTA SEETHA RAMA SWAMY,DECCAN GRAMEENA BANK ; H.O ; HYDERABAD,NaN,NaN,swamy1953nanaji@gmail.com,36 Year(s) 2 Month(s),Hyderabad/ Secunderabad,21 Aug; 2017,B.Sc. (Science),MBA/ PGDM,Rs. 9.6 lacs,9948077479,NaN
103835,Nibedita,CIBER INDIA PVT LTD,TCS New Delhi,CONSULTANT,dita.panda86@gmail.com,5 Year(s) 9 Month(s),Bengaluru/ Bangalore,21 Aug; 2017,B.Sc. (Science),NaN,Rs. 7.75 lacs,8951777490,NaN
103881,CHARLES D,Fresher,NaN,Fresher,meetme.charles@gmail.com,Fresher,Chennai,21 Aug; 2017,NaN,BCA (Computer Application),NaN,9597872600,NaN
104187,Pinnela Goutham,L & T Finance,NaN,Business Support Executive (BSE),pinnelagoutham999@gmail.com,2 Year(s),Nizamabad,21 Aug; 2017,B.Com. (Commerce),MBA/ PGDM,Rs. 1.44 lacs,9912777878,NaN
104240,CHARLES D,Fresher,NaN,Fresher,itscharles07@gmail.com,Fresher,Chennai,21 Aug; 2017,NaN,BCA (Computer Application),NaN,9597872600,NaN
104317,CHARLES D,Fresher,NaN,Fresher,itscharles06@gmail.com,Fresher,Chennai,21 Aug; 2017,NaN,BCA (Computer Application),NaN,9597872600,NaN
104722,East Marredpally,Building General Maintenance,NaN,Plumber,kerthi.saikumar@gmail.com,5 Year(s) 10 Month(s),Hyderabad/ Secunderabad,21 Aug; 2017,12th & Not Pursuing Graduation,NaN,Rs. 2.0 lacs,9885797534,NaN
105137,mahanta sushanta,sms infrastruction ltd,NaN,surveyor and civil engineer,mahanta_sushantas@yahoo.in,9 Year(s) 8 Month(s),Kolkata,21 Aug; 2017,12th & Not Pursuing Graduation,NaN,Rs. 2.4 lacs,9433806871,NaN
105169,vasant kudal,nutan plastic and rubbers,NaN,prodution engg,vasantkudal@ymail.com,1 Year(s) 6 Month(s),Hubli,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,Rs. 1.2 lacs,9845655189,NaN
105309,mahanta sushanta,sms infrastructure ltd,Vendanta Aluminium Steel Ltd,CIVIL ENGINEER,bip_1984mahanta@yahoo.in,9 Year(s) 10 Month(s),Kolkata,21 Aug; 2017,Diploma-Other Diploma,Diploma-Other Diploma,Rs. 4.2 lacs,9433806871,NaN
105312,NEHA KHURANA,homeshop 18,NaN,Customer Care Executive,sukhvinderhs18@gmail.com,3 Year(s),Noida/ Greater Noida,21 Aug; 2017,BA (Arts),NaN,Rs. 0.22 lacs,8510040901,NaN
105416,Sapna K,Deutsche Bank Operations International,Thomson Financial,Process Supervisor,asapnak@gmail.com,7 Year(s) 5 Month(s),Bengaluru/ Bangalore,21 Aug; 2017,B.Com. (Commerce),MBA/ PGDM,Rs. 7.02 lacs,9901008297,NaN
105533,K.R AMBIKA,Mantri Developers Pvt Ltd,NaN,NaN,ambikeelara@gmail.com,16 Year(s) 6 Month(s),Bengaluru/ Bangalore,21 Aug; 2017,B.Arch. (Architecture),NaN,Rs. 15.6 lacs,9448613342,NaN
105572,CHARLES D,Fresher,NaN,Fresher,charles.jayakaran@gmail.com,Fresher,Chennai,21 Aug; 2017,BCA (Computer Application),MCA/ PGDCA,NaN,9597872600,NaN
105646,Manjunatha N,Arvind Retail Limited,NaN,Head Cashier,madan.mlc@gmail.com,2 Year(s) 9 Month(s),Bengaluru/ Bangalore,21 Aug; 2017,MBA/ PGDM,NaN,Rs. 6.0 lacs,9945419366,NaN
105854,Jatin Sharma,Bristlecone India Ltd,NaN,NaN,jatincse2010@gmail.com,7 Month(s),Noida/ Greater Noida,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,Rs. 4.0 lacs,9418940338,NaN
106080,Devinder Bisht,Future Generali India Insurance Co Ltd,independent surveyor,Executive motor claims,devinder11gba07@gmail.com,5 Year(s),Delhi,21 Aug; 2017,Diploma-Other Diploma,NaN,Rs. 2.86 lacs,7838760394,NaN
106085,Manish pathak,HCL SERVICES.LTD,NaN,ENGINEER,pathakmanish38@gmail.com,3 Year(s) 2 Month(s),Gurgaon,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,Rs. 3.0 lacs,8349997748,NaN
106322,MOHAMMAD AJAZ P J,Grasim industries limited,NaN,Engineer maintenance ; Projects,ajaz200@gmail.com,3 Year(s) 10 Month(s),Bengaluru/ Bangalore,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,Rs. 3.8 lacs,9060698478,NaN
106610,Sushanta Mahanta,ahluwalia contracts india ltd,Survey / construction,Senior Engineer/Surveyor,sushant.amahanta63@gmail.com,13 Year(s) 2 Month(s),Kolkata,21 Aug; 2017,12th & Not Pursuing Graduation,Other School/ Graduation,Rs. 3.36 lacs,9433806871,NaN
106979,Dhrupal Barad,Fresher,NaN,NaN,dhrupalbarad031@gmail.com,Fresher,Ahmedabad,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,NaN,8866653619,NaN
107000,- -,Aequor Information Technologies Pvt Ltd,Cms Info Systems Pvt Ltd,NOC Administrator,mahesh.kumawat1@googlemail.com,5 Year(s) 10 Month(s),Gurgaon,21 Aug; 2017,NaN,MBA/ PGDM,Rs. 5.0 lacs,9350020321,NaN
107087,shanmuga sundar,ERP LOGIC ( INDIA ) PRIVATE LIMITED,ERP LOGIC ( INDIA ) PRIVATE LIMITED,Team Leader,shan.sndr@gmail.com,7 Year(s) 4 Month(s),Bengaluru/ Bangalore,21 Aug; 2017,NaN,MBA/ PGDM,Rs. 6.0 lacs,8344686331,NaN
107267,shailendra chaubey,bisleri international pvt ltd,BLUE LABEL,quality assured executive,shailendrachaubey_1983@rediff.com,8 Year(s),Chandigarh,21 Aug; 2017,Other School/ Graduation,MBA/ PGDM,Rs. 4.0 lacs,9646209250,NaN
107301,Swathi Thakur,Fresher,NaN,Fresher,swathi.lsthakur@gmail.com,Fresher,Bengaluru/ Bangalore,21 Aug; 2017,BE/ B.Tech (Engineering),ME/ M.Tech./ MS (Engg/ Sciences),NaN,9154572892,NaN
107547,nupoor kishor kirkise,smile automation pvt ltd,NaN,NaN,nupoor.kirkise@gmail.com,1 Year(s),Mumbai,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,Rs. 0.15 lacs,9967473190,NaN
107585,Gopal Kummera,HBL Power Systems Ltd ; Hyderabad,NaN,QA/QC Engineer,kgopalgoud@gmail.com,6 Year(s) 9 Month(s),Hyderabad/ Secunderabad,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,Rs. 3.0 lacs,9010678830,NaN
107598,Durbar De,Currently Unemployed,NaN,Currently Unemployed,durbarde90@gmail.com,1 Year(s),Kolkata,21 Aug; 2017,Other School/ Graduation,NaN,NaN,9831396184,NaN
107632,Janhavi Punjabi,Fresher,NaN,NaN,janhavivpunjabi@gmail.com,16 Year(s),Mumbai,21 Aug; 2017,B.Com. (Commerce),NaN,NaN,9820063386,NaN

In [66]:
df_10=df_10[df_10.tel_Other.apply(lambda x: if(len(str(x)))!=10),df_10.tel_Other=nan]

SyntaxError: invalid syntax (<ipython-input-66-eb05a31d958c>, line 1)

In [65]:
df_10.to_csv("data/new2.csv")

In [10]:
#final
import pandas as pd
file_name="andhra pradesh employee data. six lakh/aped.xls"
dfs = pd.read_excel(file_name, sheet_name="Sheet1")

nan_rows = dfs[dfs['Mobile_No'].isnull()]
nan_rows.to_excel("andhra pradesh employee data. six lakh/no_nos.xlsx")

df3 = pd.merge(dfs, nan_rows, how='outer', indicator=True).query('_merge=="left_only"').drop('_merge',1)


duplicateRowsDF = df3[df3.duplicated(['Mobile_No'])]
duplicateRowsDF.to_excel("andhra pradesh employee data. six lakh/duplicate.xlsx")

df3 = pd.merge(df3, duplicateRowsDF, how='outer', indicator=True).query('_merge=="left_only"').drop('_merge',1)
k_uni=df3.Mobile_No.str.split(';').str[1]

df3['alt']=k_uni

df3['Mobile_No'] = df3['Mobile_No'].str.split(';').str[0]

#remove from - fro tel_no
df3['Mobile_No'] = df3['Mobile_No'].str.split('-').str[1]
#remove from -0- from alt
#df3['alt'] = df3['alt'].str.split('-0-').str[1]

#df3.to_csv("data/unique.csv")
#convert csv to xlsx
writer = pd.ExcelWriter('andhra pradesh employee data. six lakh/unique.xlsx')
df3.to_excel(writer, index = False)
writer.save()

#alteranate number for duplicate
df_n=pd.read_excel("andhra pradesh employee data. six lakh/duplicate.xlsx",sheet_name="Sheet1")
k=df_n.Mobile_No.str.split(';').str[1]

df_n['alt']=k
df_n['Mobile_No'] = df_n['Mobile_No'].str.split(';').str[0]
#remove from - fro tel_no
df_n['Mobile_No'] = df_n['Mobile_No'].str.split('-').str[1]
#remove from -0- from alt
#df_n['alt'] = df_n['alt'].str.split('-0-').str[1]

df_n.to_excel("andhra pradesh employee data. six lakh/duplicate.xlsx")

#alteranate number for unique
#df_uni=pd.read_excel("data/unique.xlsx",sheet_name="Sheet1")
#k_uni=df_uni.tel_Other.str.split(';').str[1]

#df_uni['alt']=k_uni
#df_uni['tel_Other'] = df_uni['tel_Other'].str.split(';').str[0]
#writer_uni = pd.ExcelWriter('data/unique.xlsx')
#df_uni.to_excel(writer_uni, index = False)
#writer.save()

In [50]:
#final
import pandas as pd
file_name="data/_Aug2-107561.xlsx"
path="data/"
dfs = pd.read_excel(file_name, sheet_name="Sheet1")

nan_rows = dfs[dfs['tel_Other'].isnull()]
nan_rows['salary'] = nan_rows['salary'].str.split('s.').str[1]
nan_rows['salary'] = nan_rows['salary'].str.split('l').str[0]
nan_rows.to_excel(path+"no_nos.xlsx")

df3 = pd.merge(dfs, nan_rows, how='outer', indicator=True).query('_merge=="left_only"').drop('_merge',1)


duplicateRowsDF = df3[df3.duplicated(['tel_Other'])]
duplicateRowsDF.to_excel(path+"duplicate.xlsx")

df3 = pd.merge(df3, duplicateRowsDF, how='outer', indicator=True).query('_merge=="left_only"').drop('_merge',1)
k_uni=df3.tel_Other.str.split(';').str[1]

df3['alt']=k_uni

df3['tel_Other'] = df3['tel_Other'].str.split(';').str[0]

#remove from - fro tel_no
df3['tel_Other'] = df3['tel_Other'].str.split('-').str[1]
#remove from -0- from alt
df3['alt'] = df3['alt'].str.split('-0-').str[1]
#salary
df3['salary'] = df3['salary'].str.split('s.').str[1]
df3['salary'] = df3['salary'].str.split('l').str[0]
#df3.to_csv("data/unique.csv")
#convert csv to xlsx
writer = pd.ExcelWriter(path+'unique.xlsx')
df3.to_excel(writer, index = False)
writer.save()

#alteranate number for duplicate
df_n=pd.read_excel(path+"duplicate.xlsx",sheet_name="Sheet1")
k=df_n.tel_Other.str.split(';').str[1]

df_n['alt']=k
df_n['tel_Other'] = df_n['tel_Other'].str.split(';').str[0]
#remove from - fro tel_no
df_n['tel_Other'] = df_n['tel_Other'].str.split('-').str[1]
#remove from -0- from alt
df_n['alt'] = df_n['alt'].str.split('-0-').str[1]
#salary
df_n['salary'] = df_n['salary'].str.split('s.').str[1]
df_n['salary'] = df_n['salary'].str.split('l').str[0]

df_n.to_excel(path+"/duplicate.xlsx")

#alteranate number for unique
#df_uni=pd.read_excel("data/unique.xlsx",sheet_name="Sheet1")
#k_uni=df_uni.tel_Other.str.split(';').str[1]

#df_uni['alt']=k_uni
#df_uni['tel_Other'] = df_uni['tel_Other'].str.split(';').str[0]
#writer_uni = pd.ExcelWriter('data/unique.xlsx')
#df_uni.to_excel(writer_uni, index = False)
#writer.save()

c:\users\suma\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

c:\users\suma\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [77]:
df_1=pd.read_excel(path+"duplicate.xlsx",sheet_name="Sheet1")

In [78]:

df_1['experienceMas'] = df_1['experienceMas'].str.replace("Year(s)",'.')

In [79]:
df_1['experienceMas'] = df_1['experienceMas'].str.split('M').str[0]

In [81]:
df_1['experienceMas'] = df_1.apply(dealwithdates, axis=1)

TypeError: ("cannot convert the series to <class 'int'>", 'occurred at index 1284')

In [194]:
df_1=pd.read_excel(path+"unique.xlsx",sheet_name="Sheet1")

#

In [195]:

df_1['experienceMas'] = df_1['experienceMas'].str.split('M').str[0]

In [196]:

df_1["experienceMas"]= df_1["experienceMas"].replace("Year",'.',regex=True) 
#df_1['experienceMas'] = df_1['experienceMas'].replace({'Year(s)':'.'})

In [200]:
df_1['experienceMas'] = df_1['experienceMas'].str.replace(r"[^a-zA-Z\d\_]+", "")    
df_1['experienceMas'] = df_1['experienceMas'].str.replace("Fresher", '0',regex=True)

In [201]:
r = df_1['experienceMas'].str.split('s').str[0]
k = df_1['experienceMas'].str.split('s').str[1]

In [209]:
sum=int(r)*12+int(k)

TypeError: cannot convert the series to <class 'int'>

In [205]:
df_1['experienceMas'] = sum

In [206]:
df_1

,candidateName,companyName,companyName2,designation,emailAddress,experienceMas,locationCurrentMas,lastUpdate,qualificationMas,qualificationMas2,salary,tel_Other,alt
0,DEEPTI SINGH,Fresher,NaN,Fresher,sdeepti69@gmail.com,NaN,Delhi,16 Aug; 2017,NaN,ME/ M.Tech./ MS (Engg/ Sciences),NaN,9582274987,NaN
1,Vijaykumar Gaikwad,Wockhardt Hospitals Enterprise Ltd,NaN,pharmacy manager/ Incharge,gaikwadvijay01@gmail.com,131313131313131313131313,Mumbai,16 Aug; 2017,Diploma-Other Diploma,NaN,4.35,9819013635,NaN
2,BIBHUDUTTA DASH,Indian Metals And Ferro Alloys Ltd,Depart of Science n Technology ; Govt. Of India,Manager Raw Material,bibhu.dash@ymail.com,2020202020202020202020208,THERUBALI; RAYAGADA,16 Aug; 2017,BA (Arts),MA (Arts),8.50,9583686862,NaN
3,D MOHAN,videocon industries ltd,NaN,Accounts Officer,dmohan_kalathil@rediffmail.com,222222222222222222222222,Raipur,16 Aug; 2017,B.Com. (Commerce),NaN,4.50,9300023567,NaN
4,manojit biswas,titan industries limited,NaN,casher,manojit_ccd@rediff.com,6666666666666,Kolkata,16 Aug; 2017,B.Com. (Commerce),NaN,1.20,9830317237,NaN
5,Suraj Adhav,sotc travels & tours pvt ltd,NaN,NaN,surajadhav7@gmail.com,NaN,Pune,16 Aug; 2017,BA (Arts),NaN,2.10,9021112213,NaN
6,suryakant sakharam jadhav,Hcl Infosystems Ltd,NaN,warehouse incharge,suryakant.1386@rediffmail.com,141414141414141414141414,Mumbai,16 Aug; 2017,12th & Not Pursuing Graduation,NaN,1.32,9987952267,NaN
7,Taruna Talari,Cerebrabraintech.pvt.ltd,Shartul gurukul school for special childrens,Clinical psychologist,tarunatalari@gmail.com,22222222222211,Mumbai,16 Aug; 2017,BA (Arts),MA (Arts),2.40,9821286821,NaN
8,DEBASISH BOSE,Uti Mutual Fund,NaN,NaN,mihikamodern@gmail.com,111111111111111111111111,Dhanbad,16 Aug; 2017,NaN,MBA/ PGDM,6.00,9771427290,NaN
9,RAHUL ANANDA SARGAR,BALBHARTI,NaN,NaN,rahulsargar1000@gmail.com,111111111111,Navi Mumbai,16 Aug; 2017,BA (Arts),NaN,0.10,9594543028,NaN
10,Taheel Shaikh,VERITAS SOFTWARE PVT LTD,NaN,csa,dragonz2489@gmail.com,444444444444,Pune,16 Aug; 2017,B.Sc. (Science),NaN,4.00,9673255844,NaN
11,saipratap,Fresher,NaN,Fresher,ch.sp208@gmail.com,NaN,Hyderabad/ Secunderabad,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,NaN,9491235620,NaN
12,Padma Gowrishankar,Fresher,NaN,Fresher,padmagowrishankar@gmail.com,NaN,Pune,16 Aug; 2017,B.Ed. (Education),NaN,NaN,9881254460,NaN
13,VIKRAM SINGH,jdimt,NaN,assistant professor,singhvikram84@yahoomail.co.in,3333333333339,Varanasi / Banaras,16 Aug; 2017,B.Sc. (Science),MCA/ PGDCA,2.00,9369413296,NaN
14,Bharath B,Rangsons defence solutions pvt ltd,NaN,NaN,bharath.blr6@gmail.com,1111111111112,Bengaluru/ Bangalore,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,3.00,9880960734,NaN
15,JUDHAJIT CHOWDHURY,Fresher,NaN,Fresher,jeeetkol@gmail.com,NaN,Kolkata,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,NaN,9433250253,NaN
16,R BARAKATHULLAH,Fresher,NaN,Fresher,barkath.peace@gmail.com,NaN,Chennai,16 Aug; 2017,B.Sc. (Science),MCA/ PGDCA,NaN,9629298829,NaN
17,JAFER ABBAS,Verizon Data Services India Pvt Ltd,GAMELOFT SOFTWARE PVT. LTD,Software Engineer,abbasjafer@gmail.com,4444444444444,Hyderabad/ Secunderabad,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,6.60,9949506586,NaN
18,Asifulla khandakar,Axis Bank Ltd,NaN,relationship officer,asifkhandakar7@gmail.com,NaN,Guwahati,16 Aug; 2017,B.Com. (Commerce),NaN,1.42,8399078102,NaN
19,MANISH KUMAR,manchanda interiors pvt. ltd.,NaN,Accountant,manishksingh9999@gmail.com,141414141414141414141414,Delhi,16 Aug; 2017,B.Com. (Commerce),NaN,4.50,9756202960,NaN
20,D VIKRAM,Mu Sigma Business Solutions Pvt Ltd,NaN,Senior Decision Scientist,vikramnit2005@gmail.com,777777777777,Bengaluru/ Bangalore,16 Aug; 2017,BE/ B.Tech (Engineering),MBA/ PGDM,12.25,8334055211,NaN
21,Dr.Sushanta Kumar Mishra,Fresher,NaN,NaN,sushantakumar.mishra777@gmail.com,424242424242424242424242,Visakhapatnam,16 Aug; 2017,NaN,Ph.D. (Doctorate),NaN,9441469673,NaN
22,renu singh,Fresher,NaN,Fresher,renu.singh2793@gmail.com,NaN,Bengaluru/ Bangalore,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,NaN,9611227829,NaN
23,JANTANTRA KUMAR,bajaj securites,NaN,Stock market (Marketing) MIS data cum Client r...,jantantra.1988@gmail.com,3333333333331,Patna,16 Aug; 2017,BA (Arts),MBA/ PGDM,1.52,9798231178,NaN
24,Naveen,Nitte,NaN,NaN,naveenb0105@gmail.com,NaN,Mangalore,16 Aug; 2017,NaN,M.Com. (Commerce),0.09,8861276844,NaN
25,Puja Singh,Currently Unemployed,pacific Marketingh bhopal,Currently Unemployed,pujasingh.tomar@gmail.com,1111111111111,Hyderabad/ Secunderabad,16 Aug; 2017,BA (Arts),MBA/ PGDM,1.25,8790860066,NaN
26,DEEPAK KUSHWAHA,Fresher,NaN,Fresher,deepakkushwaha1919@gmail.com,NaN,Gwalior,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,NaN,8085102664,NaN
27,Amit Sharma,Aakash Educational Services Ltd.,NaN,sr accountant,amitk.sh2211@gmail.com,7777777777772,Delhi,16 Aug; 2017,B.Com. (Commerce),M.Com. (Commerce),3.60,8010026313,NaN
28,DANDE NAGENDRA PRASAD,START WITHUS,NaN,jr web developer,dvnagendra.92@gmail.com,1111111111112,Hyderabad/ Secunderabad,16 Aug; 2017,BE/ B.Tech (Engineering),NaN,2.10,8790507593,NaN
29,Sandeep Sharma,AGV Fenestration Pvt Ltd,Jamwal Consultant Pvt. Ltd,Assit. Accounts Manager,sandeepgph@gmail.com,6666666666668,Sirmaur,16 Aug; 2017,B.Com. (Commerce),NaN,3.40,9817017192,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
102505,Biswas Payel,Fresher,NaN,Fresher,payel30jan@gmail.com,NaN,Kolkata,21 Aug; 2017,BA (Arts),NaN,NaN,9674308418,NaN
102506,pradeep kumar.j,Fresher,NaN,Fresher,jpradeepkumarpj@gmail.com,NaN,Bengaluru/ Bangalore,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,NaN,8088417244,NaN
102507,VISHMAY PATHAK,Mumbai International Airport Pvt Ltd,NaN,Executive in Customer Service,vishmaypathak22@gmail.com,555555555555,Mumbai,21 Aug; 2017,B.Com. (Commerce),NaN,2.00,9833329927,NaN
102508,HIMANSHU TOMAR,Smart Search,NaN,Sr. Content Writer,himanshu.tomar.cw@gmail.com,333333333333,Chandigarh,21 Aug; 2017,B.Sc. (Science),NaN,1.00,9988849737,NaN
102509,ARNAB DATTA,OVARON INFRASTRUCTURE & MEP SERVICES,ISHAANI ELECTRONICS PVT LTD,Assistant Engineer,andutta.dutta@gmail.com,4444444444448,Ranchi,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,2.88,8084343704,NaN
102510,kunwar prasad,M / S Engineering ; bharuch,A R Engineering,piping supervisor,kunwarprasad658@gmail.com,3333333333332,Vadodara,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,3.00,7600705871,NaN
102511,megha,Fresher,NaN,Fresher,hedaoomegha@gmail.com,NaN,Pune,21 Aug; 2017,NaN,MCA/ PGDCA,NaN,8855076110,NaN
102512,PRAVEEN RAJ D,Fresher,NaN,Fresher,rjpraveen27@gmail.com,NaN,Chennai,21 Aug; 2017,BE/ B.Tech (Engineering),ME/ M.Tech./ MS (Engg/ Sciences),NaN,9345983910,NaN
102513,Arun Kumar,Unitedhealth Group,NaN,Sr.Claims associate,m.arun111985@gmail.com,33333333333310,Hyderabad/ Secunderabad,21 Aug; 2017,B.Com. (Commerce),NaN,3.00,7661836686,NaN
102514,Reethi Rajasekar,Fresher,NaN,Fresher,reethisunitha@gmail.com,NaN,Trichy,21 Aug; 2017,B.Sc. (Science),M.Sc. (Science),NaN,9944963161,NaN
102515,Suraj Gorwade,wipro infotech,wpri infotech,network engg,surajgorwade@gmail.com,NaN,Pune,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,1.50,9036835585,NaN
102516,Pooja Nair,Shaurya International,NaN,Online Marketing,poojanair856@gmail.com,111111111111,Jaipur,21 Aug; 2017,B.Com. (Commerce),NaN,1.50,9982502167,NaN
102517,Halim Shekh,Krish Medicare Pvt.Ltd.,NaN,NaN,shekhhalim21@gmail.com,1111111111117,Jhansi,21 Aug; 2017,B.Pharm. (Pharmacy),NaN,2.40,8931837176,NaN
102518,phaneendra.d.s,Fresher,NaN,NaN,phaneendra.d.s@gmail.com,NaN,Bengaluru/ Bangalore,21 Aug; 2017,B.Com. (Commerce),NaN,NaN,7259604197,NaN
102519,KUMAR NITIN,I MEDIA,Print Media,Sr. SEGMENT MANAGER,maheshwarinitin1983@gmail.com,4444444444446,Kolkata,21 Aug; 2017,BBA/ BBM/ BBS,MBA/ PGDM,3.22,8444801979,NaN
102520,Raja Sekaran,SBI HOME LOAN COUNSELLOR ( ON CONTRACT BASIS ),NaN,HOME LOAN COUNSELLOR,srskani@gmail.com,9999999999996,Theni,21 Aug; 2017,BBA/ BBM/ BBS,NaN,3.18,9894015315,NaN
102521,BARUN KUMAR ROY,E ZONE A FUTURE GROUP VENTURE,NaN,TEAM LEADER(Role-Department Manager),barun.royrd@gmail.com,1010101010101010101010102,Kolkata,21 Aug; 2017,12th & Not Pursuing Graduation,NaN,2.21,8486039965,NaN
102522,Harshansingh Dixit,icici bank ltd,Bharti Axa Life Insurance Company Ltd,In-Charge of Personal loans,dixit.harshan786@yahoo.in,9999999999996,Nagpur,21 Aug; 2017,BA (Arts),MBA/ PGDM,2.10,9657860693,NaN
102523,Mikky Das,Finxera,NaN,Quality Analyst,myworldmikky@gmail.com,2222222222223,Chandigarh,21 Aug; 2017,NaN,MCA/ PGDCA,4.05,8591655943,NaN
102524,arghya ghosh,Fresher,NaN,Fresher,arghyapassionghosh@gmail.com,NaN,Kolkata,21 Aug; 2017,BHM (Hotel Management),NaN,NaN,8013265848,NaN
102525,ankita vadhariya,Bmw India Pvt Ltd,NaN,NaN,ankitavadhariya@gmail.com,1111111111114,Pune,21 Aug; 2017,NaN,MBA/ PGDM,3.50,8855908908,NaN
102526,Sheetal Gaikwad,Fresher,NaN,Fresher,sheetalgaikwad68@rediffmail.com,NaN,Pune,21 Aug; 2017,NaN,M.Sc. (Science),NaN,9921885456,NaN
102527,madhura bhure,Currently Unemployed,Jabil Circuit India Pvt Ltd Pune,Currently Unemployed,madhurabhure1991@gmail.com,2222222222224,Pune,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,3.38,9975154754,NaN
102528,Naveen Kumar,IBM India Pvt Ltd,NaN,Technical Services Specialist,naveennandu20@gmail.com,4444444444445,Hyderabad/ Secunderabad,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,5.70,9700584583,NaN
102529,Regan Dias,Atos Pvt Ltd,NaN,Service Desk,regandias@yahoo.com,NaN,Mumbai,21 Aug; 2017,B.Com. (Commerce),NaN,2.00,9637331498,NaN
102530,mustak khan,Fresher,NaN,Fresher,kmustak94@yahoo.com,1111111111112,Mumbai,21 Aug; 2017,12th & Not Pursuing Graduation,12th & Not Pursuing Graduation,NaN,9819089140,NaN
102531,saurabh sharma,Vee Technologies Pvt Ltd,NaN,Medical coder,sorv.1920@gmail.com,NaN,Chennai,21 Aug; 2017,B.Pharm. (Pharmacy),NaN,1.56,9514131202,NaN
102532,sanjeev,Ericsson Global Services India Pvt Ltd,NaN,RF Engineer 4G(VoLTE),sanjeevrf50@gmail.com,444444444444,Bengaluru/ Bangalore,21 Aug; 2017,BE/ B.Tech (Engineering),NaN,5.50,9215000154,NaN
102533,GIRISH KAUSHIK,Indian Navy,NaN,Marine Commando Petty Officer I class,garry.kaushik@gmail.com,151515151515151515151515,Mumbai,21 Aug; 2017,BA (Arts),NaN,7.20,9552917339,NaN
102534,PATHAN JISHAN R,Honda Motorcycle & Scooter India Pvt Ltd,NaN,Computer Oprater,pathanjishan2@gmail.com,2222222222226,PALANPUR,21 Aug; 2017,BCA (Computer Application),NaN,0.10,8140843288,NaN